### ISSUE TITLE
Install on otrs 4.0.x 

### ISSUE THREAD

**Issue by trindium** [denydias/otrs#8]
Hi, Im trying to install you modulle ( by the way, i was looking for this for a long time)

But i can not install it. i got the following error.

```
Backend ERROR: OTRS-CGI-43 Perl: 5.14.2 OS: linux Time: Sat Nov 7 21:51:47 2015
Message: Invalid Package!
RemoteAddress: 192.168.0.99 RequestURI: /otrs/index.pl Traceback (1697):
Module: Kernel::System::Package::RepositoryAdd Line: 330
Module: Kernel::System::Package::PackageInstall Line: 567
Module: Kernel::Modules::AdminPackageManager::_InstallHandling Line: 1849
Module: Kernel::Modules::AdminPackageManager::Run Line: 1245
Module: Kernel::System::Web::InterfaceAgent::Run Line: 991
Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 41
Module: (eval) (v1.99) Line: 204
Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
Module: ModPerl::Registry::handler (v1.99) Line: 31
```

Any idea ? 

Regards

**Comment by trindium** [comment]
Debian 7, nothing strage running, im performing an upgrade just in case...

**Comment by denydias** [comment]
Hi, @trindium.

I'm sorry you're facing issues to get the add-on working for you.

How are you trying to install it? Did you get the zip file from the release section here or is trying to install it from [OPAR](http://opar.perl-services.de/dist/SupportQuota-1.0.3)?

If both has failed, can you please try an older release from [here](https://github.com/denydias/otrs/releases)?

Also, what is the exact OTRS version you're running? I have it running at production with OTRS 4.0.13 and the install is fine.

**Comment by trindium** [comment]
Deny, thx for the reply,  I will update to 4.0.13 and try again.

I installed on 5.0 and it worked,  but widget did not show on ticket
screen.

I will let you know.

Thx again
From Argentina
Juan

**Comment by denydias** [comment]
@trindium,

Support Quota Add-on is not compatible with OTRS 5x yet. It may get installed fine, but the underlying code most probably will not work as expected as you have figured out.

Please, let me know if it have worked for you under 4.0.13. Tks.

**Comment by trindium** [comment]
Will do thx

**Comment by trindium** [comment]
4.0.14 works like a charm... :D

Seems that 4.0.10 was the problem.

Thx for the reply..


Hope you can work on getting it working on 5.0, its a very nice upgrade on
otrs.

bye

See u Soon, At the dark side of the Moon

**Comment by denydias** [comment]
Glad to hear that, @trindium!

OTRS 4.0.8 to 10 was a real mess! Many [things](http://bugs.otrs.org/show_bug.cgi?id=11295) broken there.

About 5x, don't hold your breath. I'm slowly discontinuing OTRS at production servers...
