### ISSUE TITLE
Monthly Restart of Quota

### ISSUE THREAD

**Issue by trindium** [denydias/otrs#9]
Hi Deny.... I was wondering if i need to do anything so on a new month customers quota is restarted.

Thanks in advance.

Juan

PS: I was looking for someone to do some freelance job to update your module to otrs5, dont know if you do any freelance jobs, or know someone that knows your module and wants to ??

**Comment by denydias** [comment]
@trindium,

If you have set it `SupportQuota::Preferences::Recurrence` to `monthly` at SysConfig, it should reset the available and used quotas on each month.

Regarding OTRS5, drop me a line: deny at macpress dot com dot br.

**Comment by trindium** [comment]
Deny, i have but asi dicember started nothing happened.... :(

Anything i can look ?


See u Soon, At the dark side of the Moon

**Comment by denydias** [comment]
I'll check that in my development environment later today. Get back to you soon.

**Comment by trindium** [comment]
Thx... let me know if i can send you any log

See u Soon, At the dark side of the Moon

**Comment by denydias** [comment]
I can confirm this issue. Working on it.

**Comment by denydias** [comment]
@trindium, it should be fixed now. A new [release](https://github.com/denydias/otrs/releases/tag/v1.0.4) is available, thanks to you.

It's working just fine on both my development and production environments.
